package com.plc.hmi.dal.mapper;

import com.plc.hmi.dal.entity.PressureProgramEntity;
import org.apache.ibatis.annotations.*;

import java.util.HashMap;
import java.util.List;

@Mapper
public interface PressureProgramMapper {
    @Select("select * from pressure_program where is_deleted='0' and PRODUCT_ID=#{productId}")
    @Results({
            @Result(id=true,column = "ID",property = "id" ),
            @Result(column = "PRODUCT_ID",property ="productId"),
            @Result(column = "PRODUCT_CODE",property ="productCode"),
            @Result(column = "STEP_1",property ="step1"),
            @Result(column = "STEP_2",property ="step2"),
            @Result(column = "STEP_3",property ="step3"),
            @Result(column = "STEP_4",property ="step4"),
            @Result(column = "STEP_5",property ="step5"),
            @Result(column = "STEP_6",property ="step6"),
            @Result(column = "STEP_7",property ="step7"),
            @Result(column = "STEP_8",property ="step8"),
            @Result(column = "PROGRAM_TYPE_1",property ="programType1"),
            @Result(column = "PROGRAM_TYPE_2",property ="programType2"),
            @Result(column = "PROGRAM_TYPE_3",property ="programType3"),
            @Result(column = "PROGRAM_TYPE_4",property ="programType4"),
            @Result(column = "PROGRAM_TYPE_5",property ="programType5"),
            @Result(column = "PROGRAM_TYPE_6",property ="programType6"),
            @Result(column = "PROGRAM_TYPE_7",property ="programType7"),
            @Result(column = "PROGRAM_TYPE_8",property ="programType8"),
            @Result(column = "PROGRAM_VALUE_1",property ="programValue1"),
            @Result(column = "PROGRAM_VALUE_2",property ="programValue2"),
            @Result(column = "PROGRAM_VALUE_3",property ="programValue3"),
            @Result(column = "PROGRAM_VALUE_4",property ="programValue4"),
            @Result(column = "PROGRAM_VALUE_5",property ="programValue5"),
            @Result(column = "PROGRAM_VALUE_6",property ="programValue6"),
            @Result(column = "PROGRAM_VALUE_7",property ="programValue7"),
            @Result(column = "PROGRAM_VALUE_8",property ="programValue8"),
            @Result(column = "SPEED_1",property ="speed1"),
            @Result(column = "SPEED_2",property ="speed2"),
            @Result(column = "SPEED_3",property ="speed3"),
            @Result(column = "SPEED_4",property ="speed4"),
            @Result(column = "SPEED_5",property ="speed5"),
            @Result(column = "SPEED_6",property ="speed6"),
            @Result(column = "SPEED_7",property ="speed7"),
            @Result(column = "SPEED_8",property ="speed8"),
            @Result(column = "ALARM_DEAL_TYPE_1",property ="alarmDealType1"),
            @Result(column = "ALARM_DEAL_TYPE_2",property ="alarmDealType2"),
            @Result(column = "ALARM_DEAL_TYPE_3",property ="alarmDealType3"),
            @Result(column = "ALARM_DEAL_TYPE_4",property ="alarmDealType4"),
            @Result(column = "ALARM_DEAL_TYPE_5",property ="alarmDealType5"),
            @Result(column = "ALARM_DEAL_TYPE_6",property ="alarmDealType6"),
            @Result(column = "ALARM_DEAL_TYPE_7",property ="alarmDealType7"),
            @Result(column = "ALARM_DEAL_TYPE_8",property ="alarmDealType8"),
            @Result(column = "POSITION_1",property ="position1"),
            @Result(column = "POSITION_2",property ="position2"),
            @Result(column = "POSITION_3",property ="position3"),
            @Result(column = "POSITION_4",property ="position4"),
            @Result(column = "POSITION_5",property ="position5"),
            @Result(column = "POSITION_6",property ="position6"),
            @Result(column = "POSITION_7",property ="position7"),
            @Result(column = "POSITION_8",property ="position8"),
            @Result(column = "PROTECT_PRESS_1",property ="protectPress1"),
            @Result(column = "PROTECT_PRESS_2",property ="protectPress2"),
            @Result(column = "PROTECT_PRESS_3",property ="protectPress3"),
            @Result(column = "PROTECT_PRESS_4",property ="protectPress4"),
            @Result(column = "PROTECT_PRESS_5",property ="protectPress5"),
            @Result(column = "PROTECT_PRESS_6",property ="protectPress6"),
            @Result(column = "PROTECT_PRESS_7",property ="protectPress7"),
            @Result(column = "PROTECT_PRESS_8",property ="protectPress8"),
            @Result(column = "PRESS_1",property ="press1"),
            @Result(column = "PRESS_2",property ="press2"),
            @Result(column = "PRESS_3",property ="press3"),
            @Result(column = "PRESS_4",property ="press4"),
            @Result(column = "PRESS_5",property ="press5"),
            @Result(column = "PRESS_6",property ="press6"),
            @Result(column = "PRESS_7",property ="press7"),
            @Result(column = "PRESS_8",property ="press8"),
            @Result(column = "PROTECT_POSITION_1",property ="protectPosition1"),
            @Result(column = "PROTECT_POSITION_2",property ="protectPosition2"),
            @Result(column = "PROTECT_POSITION_3",property ="protectPosition3"),
            @Result(column = "PROTECT_POSITION_4",property ="protectPosition4"),
            @Result(column = "PROTECT_POSITION_5",property ="protectPosition5"),
            @Result(column = "PROTECT_POSITION_6",property ="protectPosition6"),
            @Result(column = "PROTECT_POSITION_7",property ="protectPosition7"),
            @Result(column = "PROTECT_POSITION_8",property ="protectPosition8"),
            @Result(column = "PROTECT_TIME_1",property ="protectTime1"),
            @Result(column = "PROTECT_TIME_2",property ="protectTime2"),
            @Result(column = "PROTECT_TIME_3",property ="protectTime3"),
            @Result(column = "PROTECT_TIME_4",property ="protectTime4"),
            @Result(column = "PROTECT_TIME_5",property ="protectTime5"),
            @Result(column = "PROTECT_TIME_6",property ="protectTime6"),
            @Result(column = "PROTECT_TIME_7",property ="protectTime7"),
            @Result(column = "PROTECT_TIME_8",property ="protectTime8"),
            @Result(column = "ERRAND_TYPE_1",property ="errandType1"),
            @Result(column = "ERRAND_TYPE_2",property ="errandType2"),
            @Result(column = "ERRAND_TYPE_3",property ="errandType3"),
            @Result(column = "ERRAND_TYPE_4",property ="errandType4"),
            @Result(column = "ERRAND_TYPE_5",property ="errandType5"),
            @Result(column = "POSITION_MIN_1",property ="positionMin1"),
            @Result(column = "POSITION_MIN_2",property ="positionMin2"),
            @Result(column = "POSITION_MIN_3",property ="positionMin3"),
            @Result(column = "POSITION_MIN_4",property ="positionMin4"),
            @Result(column = "POSITION_MIN_5",property ="positionMin5"),
            @Result(column = "POSITION_MAX_1",property ="positionMax1"),
            @Result(column = "POSITION_MAX_2",property ="positionMax2"),
            @Result(column = "POSITION_MAX_3",property ="positionMax3"),
            @Result(column = "POSITION_MAX_4",property ="positionMax4"),
            @Result(column = "POSITION_MAX_5",property ="positionMax5"),
            @Result(column = "PRESS_MIN_1",property ="pressMin1"),
            @Result(column = "PRESS_MIN_2",property ="pressMin2"),
            @Result(column = "PRESS_MIN_3",property ="pressMin3"),
            @Result(column = "PRESS_MIN_4",property ="pressMin4"),
            @Result(column = "PRESS_MIN_5",property ="pressMin5"),
            @Result(column = "PRESS_MAX_1",property ="pressMax1"),
            @Result(column = "PRESS_MAX_2",property ="pressMax2"),
            @Result(column = "PRESS_MAX_3",property ="pressMax3"),
            @Result(column = "PRESS_MAX_4",property ="pressMax4"),
            @Result(column = "PRESS_MAX_5",property ="pressMax5"),
            @Result(column = "CREATE_BY",property = "createBy"),
            @Result(column = "UPDATE_BY",property = "updateBy"),
            @Result(column = "CREATE_TIME",property = "createTime"),
            @Result(column = "UPDATE_TIME",property = "updateTime"),
            @Result(column = "IS_DELETED",property = "isDeleted"),
    })
    List<PressureProgramEntity> getWithProductId(@Param("productId") Long productId);

    @Select("select * from pressure_program where is_deleted='0'")
    @Results({
            @Result(id=true,column = "ID",property = "id" ),
            @Result(column = "PRODUCT_ID",property ="productId"),
            @Result(column = "PRODUCT_CODE",property ="productCode"),
            @Result(column = "STEP_1",property ="step1"),
            @Result(column = "STEP_2",property ="step2"),
            @Result(column = "STEP_3",property ="step3"),
            @Result(column = "STEP_4",property ="step4"),
            @Result(column = "STEP_5",property ="step5"),
            @Result(column = "STEP_6",property ="step6"),
            @Result(column = "STEP_7",property ="step7"),
            @Result(column = "STEP_8",property ="step8"),
            @Result(column = "PROGRAM_TYPE_1",property ="programType1"),
            @Result(column = "PROGRAM_TYPE_2",property ="programType2"),
            @Result(column = "PROGRAM_TYPE_3",property ="programType3"),
            @Result(column = "PROGRAM_TYPE_4",property ="programType4"),
            @Result(column = "PROGRAM_TYPE_5",property ="programType5"),
            @Result(column = "PROGRAM_TYPE_6",property ="programType6"),
            @Result(column = "PROGRAM_TYPE_7",property ="programType7"),
            @Result(column = "PROGRAM_TYPE_8",property ="programType8"),
            @Result(column = "PROGRAM_VALUE_1",property ="programValue1"),
            @Result(column = "PROGRAM_VALUE_2",property ="programValue2"),
            @Result(column = "PROGRAM_VALUE_3",property ="programValue3"),
            @Result(column = "PROGRAM_VALUE_4",property ="programValue4"),
            @Result(column = "PROGRAM_VALUE_5",property ="programValue5"),
            @Result(column = "PROGRAM_VALUE_6",property ="programValue6"),
            @Result(column = "PROGRAM_VALUE_7",property ="programValue7"),
            @Result(column = "PROGRAM_VALUE_8",property ="programValue8"),
            @Result(column = "SPEED_1",property ="speed1"),
            @Result(column = "SPEED_2",property ="speed2"),
            @Result(column = "SPEED_3",property ="speed3"),
            @Result(column = "SPEED_4",property ="speed4"),
            @Result(column = "SPEED_5",property ="speed5"),
            @Result(column = "SPEED_6",property ="speed6"),
            @Result(column = "SPEED_7",property ="speed7"),
            @Result(column = "SPEED_8",property ="speed8"),
            @Result(column = "ALARM_DEAL_TYPE_1",property ="alarmDealType1"),
            @Result(column = "ALARM_DEAL_TYPE_2",property ="alarmDealType2"),
            @Result(column = "ALARM_DEAL_TYPE_3",property ="alarmDealType3"),
            @Result(column = "ALARM_DEAL_TYPE_4",property ="alarmDealType4"),
            @Result(column = "ALARM_DEAL_TYPE_5",property ="alarmDealType5"),
            @Result(column = "ALARM_DEAL_TYPE_6",property ="alarmDealType6"),
            @Result(column = "ALARM_DEAL_TYPE_7",property ="alarmDealType7"),
            @Result(column = "ALARM_DEAL_TYPE_8",property ="alarmDealType8"),
            @Result(column = "POSITION_1",property ="position1"),
            @Result(column = "POSITION_2",property ="position2"),
            @Result(column = "POSITION_3",property ="position3"),
            @Result(column = "POSITION_4",property ="position4"),
            @Result(column = "POSITION_5",property ="position5"),
            @Result(column = "POSITION_6",property ="position6"),
            @Result(column = "POSITION_7",property ="position7"),
            @Result(column = "POSITION_8",property ="position8"),
            @Result(column = "PROTECT_PRESS_1",property ="protectPress1"),
            @Result(column = "PROTECT_PRESS_2",property ="protectPress2"),
            @Result(column = "PROTECT_PRESS_3",property ="protectPress3"),
            @Result(column = "PROTECT_PRESS_4",property ="protectPress4"),
            @Result(column = "PROTECT_PRESS_5",property ="protectPress5"),
            @Result(column = "PROTECT_PRESS_6",property ="protectPress6"),
            @Result(column = "PROTECT_PRESS_7",property ="protectPress7"),
            @Result(column = "PROTECT_PRESS_8",property ="protectPress8"),
            @Result(column = "PRESS_1",property ="press1"),
            @Result(column = "PRESS_2",property ="press2"),
            @Result(column = "PRESS_3",property ="press3"),
            @Result(column = "PRESS_4",property ="press4"),
            @Result(column = "PRESS_5",property ="press5"),
            @Result(column = "PRESS_6",property ="press6"),
            @Result(column = "PRESS_7",property ="press7"),
            @Result(column = "PRESS_8",property ="press8"),
            @Result(column = "PROTECT_POSITION_1",property ="protectPosition1"),
            @Result(column = "PROTECT_POSITION_2",property ="protectPosition2"),
            @Result(column = "PROTECT_POSITION_3",property ="protectPosition3"),
            @Result(column = "PROTECT_POSITION_4",property ="protectPosition4"),
            @Result(column = "PROTECT_POSITION_5",property ="protectPosition5"),
            @Result(column = "PROTECT_POSITION_6",property ="protectPosition6"),
            @Result(column = "PROTECT_POSITION_7",property ="protectPosition7"),
            @Result(column = "PROTECT_POSITION_8",property ="protectPosition8"),
            @Result(column = "PROTECT_TIME_1",property ="protectTime1"),
            @Result(column = "PROTECT_TIME_2",property ="protectTime2"),
            @Result(column = "PROTECT_TIME_3",property ="protectTime3"),
            @Result(column = "PROTECT_TIME_4",property ="protectTime4"),
            @Result(column = "PROTECT_TIME_5",property ="protectTime5"),
            @Result(column = "PROTECT_TIME_6",property ="protectTime6"),
            @Result(column = "PROTECT_TIME_7",property ="protectTime7"),
            @Result(column = "PROTECT_TIME_8",property ="protectTime8"),
            @Result(column = "ERRAND_TYPE_1",property ="errandType1"),
            @Result(column = "ERRAND_TYPE_2",property ="errandType2"),
            @Result(column = "ERRAND_TYPE_3",property ="errandType3"),
            @Result(column = "ERRAND_TYPE_4",property ="errandType4"),
            @Result(column = "ERRAND_TYPE_5",property ="errandType5"),
            @Result(column = "POSITION_MIN_1",property ="positionMin1"),
            @Result(column = "POSITION_MIN_2",property ="positionMin2"),
            @Result(column = "POSITION_MIN_3",property ="positionMin3"),
            @Result(column = "POSITION_MIN_4",property ="positionMin4"),
            @Result(column = "POSITION_MIN_5",property ="positionMin5"),
            @Result(column = "POSITION_MAX_1",property ="positionMax1"),
            @Result(column = "POSITION_MAX_2",property ="positionMax2"),
            @Result(column = "POSITION_MAX_3",property ="positionMax3"),
            @Result(column = "POSITION_MAX_4",property ="positionMax4"),
            @Result(column = "POSITION_MAX_5",property ="positionMax5"),
            @Result(column = "PRESS_MIN_1",property ="pressMin1"),
            @Result(column = "PRESS_MIN_2",property ="pressMin2"),
            @Result(column = "PRESS_MIN_3",property ="pressMin3"),
            @Result(column = "PRESS_MIN_4",property ="pressMin4"),
            @Result(column = "PRESS_MIN_5",property ="pressMin5"),
            @Result(column = "PRESS_MAX_1",property ="pressMax1"),
            @Result(column = "PRESS_MAX_2",property ="pressMax2"),
            @Result(column = "PRESS_MAX_3",property ="pressMax3"),
            @Result(column = "PRESS_MAX_4",property ="pressMax4"),
            @Result(column = "PRESS_MAX_5",property ="pressMax5"),
            @Result(column = "CREATE_BY",property = "createBy"),
            @Result(column = "UPDATE_BY",property = "updateBy"),
            @Result(column = "CREATE_TIME",property = "createTime"),
            @Result(column = "UPDATE_TIME",property = "updateTime"),
            @Result(column = "IS_DELETED",property = "isDeleted"),
    })
    List<PressureProgramEntity> getAllDatas();

    @Insert({"insert into pressure_program(id, PRODUCT_ID, PRODUCT_CODE, STEP_1,PROGRAM_TYPE_1, PROGRAM_VALUE_1, SPEED_1, ALARM_DEAL_TYPE_1, POSITION_1, PROTECT_PRESS_1,PRESS_1,PROTECT_POSITION_1,PROTECT_TIME_1, STEP_2,PROGRAM_TYPE_2, PROGRAM_VALUE_2, SPEED_2, ALARM_DEAL_TYPE_2, POSITION_2, PROTECT_PRESS_2,PRESS_2,PROTECT_POSITION_2,PROTECT_TIME_2, STEP_3,PROGRAM_TYPE_3, PROGRAM_VALUE_3, SPEED_3, ALARM_DEAL_TYPE_3, POSITION_3, PROTECT_PRESS_3,PRESS_3,PROTECT_POSITION_3,PROTECT_TIME_3, STEP_4,PROGRAM_TYPE_4, PROGRAM_VALUE_4, SPEED_4, ALARM_DEAL_TYPE_4, POSITION_4, PROTECT_PRESS_4,PRESS_4,PROTECT_POSITION_4,PROTECT_TIME_4, STEP_5,PROGRAM_TYPE_5, PROGRAM_VALUE_5, SPEED_5, ALARM_DEAL_TYPE_5, POSITION_5, PROTECT_PRESS_5,PRESS_5,PROTECT_POSITION_5,PROTECT_TIME_5, STEP_6,PROGRAM_TYPE_6, PROGRAM_VALUE_6, SPEED_6, ALARM_DEAL_TYPE_6, POSITION_6, PROTECT_PRESS_6,PRESS_6,PROTECT_POSITION_6,PROTECT_TIME_6, STEP_7,PROGRAM_TYPE_7, PROGRAM_VALUE_7, SPEED_7, ALARM_DEAL_TYPE_7, POSITION_7, PROTECT_PRESS_7,PRESS_7,PROTECT_POSITION_7,PROTECT_TIME_7, STEP_8,PROGRAM_TYPE_8, PROGRAM_VALUE_8, SPEED_8, ALARM_DEAL_TYPE_8, POSITION_8, PROTECT_PRESS_8,PRESS_8,PROTECT_POSITION_8,PROTECT_TIME_8,ERRAND_TYPE_1,POSITION_MIN_1,POSITION_MAX_1,PRESS_MIN_1, PRESS_MAX_1,ERRAND_TYPE_2,POSITION_MIN_2,POSITION_MAX_2,PRESS_MIN_2, PRESS_MAX_2,ERRAND_TYPE_3,POSITION_MIN_3,POSITION_MAX_3,PRESS_MIN_3, PRESS_MAX_3,ERRAND_TYPE_4,POSITION_MIN_4,POSITION_MAX_4,PRESS_MIN_4, PRESS_MAX_4,ERRAND_TYPE_5,POSITION_MIN_5,POSITION_MAX_5,PRESS_MIN_5, PRESS_MAX_5, IS_DELETED, CREATE_BY, UPDATE_BY,CREATE_TIME,UPDATE_TIME) values(null, #{productId}, #{productCode}, #{step1}, #{programType1}, #{programValue1}, #{speed1}, #{alarmDealType1}, #{position1}, #{protectPress1}, #{press1}, #{protectPosition1}, #{protectTime1}, #{step2}, #{programType2}, #{programValue2}, #{speed2}, #{alarmDealType2}, #{position2},#{protectPress2},  #{press2}, #{protectPosition2}, #{protectTime2}, #{step3}, #{programType3}, #{programValue3}, #{speed3}, #{alarmDealType3}, #{position3}, #{protectPress3}, #{press3}, #{protectPosition3}, #{protectTime3},  #{step4}, #{programType4}, #{programValue4}, #{speed4}, #{alarmDealType4}, #{position4}, #{protectPress4}, #{press4}, #{protectPosition4}, #{protectTime4},  #{step5}, #{programType5}, #{programValue5}, #{speed5}, #{alarmDealType5}, #{position5}, #{protectPress5}, #{press5}, #{protectPosition5}, #{protectTime5},  #{step6}, #{programType6}, #{programValue6}, #{speed6}, #{alarmDealType6}, #{position6}, #{protectPress6}, #{press6}, #{protectPosition6}, #{protectTime6},  #{step7}, #{programType7}, #{programValue7}, #{speed7}, #{alarmDealType7}, #{position7}, #{protectPress7}, #{press7}, #{protectPosition7}, #{protectTime7},  #{step8}, #{programType8}, #{programValue8}, #{speed8}, #{alarmDealType8}, #{position8}, #{protectPress8}, #{press8}, #{protectPosition8}, #{protectTime8}, #{errandType1}, #{positionMin1}, #{positionMax1}, #{pressMin1}, #{pressMax1},#{errandType2}, #{positionMin2}, #{positionMax2}, #{pressMin2}, #{pressMax2}, #{errandType3}, #{positionMin3}, #{positionMax3}, #{pressMin3}, #{pressMax3}, #{errandType4}, #{positionMin4}, #{positionMax4}, #{pressMin4}, #{pressMax4}, #{errandType5}, #{positionMin5}, #{positionMax5}, #{pressMin5}, #{pressMax5},'0', #{createBy}, #{createBy}, now(), now())"})
    void insert(PressureProgramEntity entity);

    @Update({"update pressure_program set PRODUCT_ID=#{productId}, PRODUCT_CODE=#{productCode}, STEP_1=#{step1},PROGRAM_TYPE_1=#{programType1},PROGRAM_VALUE_1=#{programValue1},SPEED_1=#{speed1}, ALARM_DEAL_TYPE_1=#{alarmDealType1}, POSITION_1=#{position1}, PROTECT_PRESS_1=#{protectPress1}, PRESS_1=#{press1}, PROTECT_POSITION_1=#{protectPosition1}, PROTECT_TIME_1=#{protectTime1},STEP_2=#{step2},PROGRAM_TYPE_2=#{programType2},PROGRAM_VALUE_2=#{programValue2},SPEED_2=#{speed2}, ALARM_DEAL_TYPE_2=#{alarmDealType2}, POSITION_2=#{position2}, PROTECT_PRESS_2=#{protectPress2}, PRESS_2=#{press2}, PROTECT_POSITION_2=#{protectPosition2}, PROTECT_TIME_2=#{protectTime2},STEP_3=#{step3},PROGRAM_TYPE_3=#{programType3},PROGRAM_VALUE_3=#{programValue3},SPEED_3=#{speed3}, ALARM_DEAL_TYPE_3=#{alarmDealType3}, POSITION_3=#{position3}, PROTECT_PRESS_3=#{protectPress3}, PRESS_3=#{press3}, PROTECT_POSITION_3=#{protectPosition3}, PROTECT_TIME_3=#{protectTime3},STEP_4=#{step4},PROGRAM_TYPE_4=#{programType4},PROGRAM_VALUE_4=#{programValue4},SPEED_4=#{speed4}, ALARM_DEAL_TYPE_4=#{alarmDealType4}, POSITION_4=#{position4}, PROTECT_PRESS_4=#{protectPress4}, PRESS_4=#{press4}, PROTECT_POSITION_4=#{protectPosition4}, PROTECT_TIME_4=#{protectTime4},STEP_5=#{step5},PROGRAM_TYPE_5=#{programType5},PROGRAM_VALUE_5=#{programValue5},SPEED_5=#{speed5}, ALARM_DEAL_TYPE_5=#{alarmDealType5}, POSITION_5=#{position5}, PROTECT_PRESS_5=#{protectPress5}, PRESS_5=#{press5}, PROTECT_POSITION_5=#{protectPosition5}, PROTECT_TIME_5=#{protectTime5},STEP_6=#{step6},PROGRAM_TYPE_6=#{programType6},PROGRAM_VALUE_6=#{programValue6},SPEED_6=#{speed6}, ALARM_DEAL_TYPE_6=#{alarmDealType6}, POSITION_6=#{position6}, PROTECT_PRESS_6=#{protectPress6}, PRESS_6=#{press6}, PROTECT_POSITION_6=#{protectPosition6}, PROTECT_TIME_6=#{protectTime6},STEP_7=#{step7},PROGRAM_TYPE_7=#{programType7},PROGRAM_VALUE_7=#{programValue7},SPEED_7=#{speed7}, ALARM_DEAL_TYPE_7=#{alarmDealType7}, POSITION_7=#{position7}, PROTECT_PRESS_7=#{protectPress7}, PRESS_7=#{press7}, PROTECT_POSITION_7=#{protectPosition7}, PROTECT_TIME_7=#{protectTime7},STEP_8=#{step8},PROGRAM_TYPE_8=#{programType8},PROGRAM_VALUE_8=#{programValue8},SPEED_8=#{speed8}, ALARM_DEAL_TYPE_8=#{alarmDealType8}, POSITION_8=#{position8}, PROTECT_PRESS_8=#{protectPress8}, PRESS_8=#{press8}, PROTECT_POSITION_8=#{protectPosition8}, PROTECT_TIME_8=#{protectTime8},ERRAND_TYPE_1=#{errandType1},POSITION_MIN_1=#{positionMin1},POSITION_MAX_1=#{positionMax1},PRESS_MIN_1=#{pressMin1}, PRESS_MAX_1=#{pressMax1},ERRAND_TYPE_2=#{errandType2},POSITION_MIN_2=#{positionMin2},POSITION_MAX_2=#{positionMax2},PRESS_MIN_2=#{pressMin2}, PRESS_MAX_2=#{pressMax2},ERRAND_TYPE_3=#{errandType3},POSITION_MIN_3=#{positionMin3},POSITION_MAX_3=#{positionMax3},PRESS_MIN_3=#{pressMin3}, PRESS_MAX_3=#{pressMax3},ERRAND_TYPE_4=#{errandType4},POSITION_MIN_4=#{positionMin4},POSITION_MAX_4=#{positionMax4},PRESS_MIN_4=#{pressMin4}, PRESS_MAX_4=#{pressMax4},ERRAND_TYPE_5=#{errandType5},POSITION_MIN_5=#{positionMin5},POSITION_MAX_5=#{positionMax5},PRESS_MIN_5=#{pressMin5}, PRESS_MAX_5=#{pressMax5},UPDATE_BY= #{updateBy},  UPDATE_TIME=now() where ID=#{id}"})
    void update(PressureProgramEntity entity);

    @Update({"update pressure_program set  IS_DELETED='1', UPDATE_BY= #{updateBy}, UPDATE_TIME=now() where ID=#{id}"})
    void delete(PressureProgramEntity entity);
}
